directories:
  output: release
  buildResources: build
appId: com.wahtway.app
productName: WahtWay
files:
  - filter:
      - electron/**/*
      - be/dist/**/*
      - be/data/**/*
      - be/node_modules/**/*
      - be/package.json
      - dist/**/*
win:
  target: portable
  sign: null
nsis:
  oneClick: false
asar: false
electronVersion: 33.4.11
